### ISSUE TITLE
Challenge contract deployment action seems to fail without trace 

### ISSUE THREAD

**Issue by StrixSC** [chainflag/eth-challenge-base#18]
Hello again!

I seem to have a few issues regarding the deployment of my contract with the image from https://github.com/chainflag/ctf-eth-env.

When I deploy my contract and I use `web3.eth.getCode()` in the geth console, the contract seems to have failed to deploy, since the returned value is `0x`:

```bash
$ nc 127.0.0.1 20000                                                                                                                                                  

We design a pretty easy contract challenge. Enjoy it!
Your goal is to make isSolved() function returns true!

[1] - Create an account which will be used to deploy the challenge contract
[2] - Deploy the challenge contract using your generated account
[3] - Get your flag once you meet the requirement
[4] - Show the contract source code
[-] input your choice: 2
[-] input your token: v4.local.oTuLapGiLip4sN8Xeq4ybs4I7mSrjqBDcBpWfbvG52pLza7_ApYZFTVE5I8Iim2_6ghuVcEfhtsqWMJZtelJYd5xYvw0snfi3QgXDMUVE1FWmdMathorVQIfDCwDw04B8MzZVdzgnVMI9bpZ3R-xc7eojYxa5PosF-TqK9VzgwX2oA
[+] contract address: 0xCE598ED0e36dD47D376ad524666036CAFc31A0E8
[+] transaction hash: 0x2ae4e59f72051abe409a5664f03db3162537f081eb3cc2dceb93d6d378f0ee28

$ geth attach http://127.0.0.1:8545 
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.15-stable-8be800ff/linux-amd64/go1.17.5
coinbase: 0x7723d574e25d448e5c55d03fccf09d077f3776ce
at block: 40425 (Tue Jan 25 2022 02:14:08 GMT-0500 (EST))
 modules: debug:1.0 eth:1.0 net:1.0 rpc:1.0 web3:1.0

To exit, press ctrl-d or type exit
> web3.eth.getCode("0xCE598ED0e36dD47D376ad524666036CAFc31A0E8")
"0x"

```

I tried the example you provided with `Greeter.sol`, and when deploying the contract, I get valid hexcode when checking with `web3.eth.getCode`.

Furthermore, when I try to get the flag using the 3rd action, I get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 1515, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ctf/run.py", line 50, in <module>
    main()
  File "/home/ctf/run.py", line 46, in main
    sys.exit(actions[choice].handler())
  File "/home/ctf/eth_challenge_base/action.py", line 166, in action
    is_solved = self._contract.at(contract_addr).isSolved().call()
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 1532, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```

So I am keen to believe there was an error during the creation of the contract lol!

The contract is as follows, I tried to respect the convention I found in Greeter, as well as the one found in some other examples where the image was used:

```solidity
pragma solidity ^0.8.7;

contract SDGG {
    event GuessTriggered(uint256 _number, string _result);
    event GameStarted();
    event GameEnded();
    event GameWon();
    event GameLost();

    mapping(uint256 => uint256) private _generator;
    uint256 private _generatorSize;
    address private _owner;
    uint256 private MIN_WORD_LENGTH = 1;
    uint256 private gameCost = 0.001 ether;
    uint8 private MAX_GUESSES = 1;
    uint8 private _guessCount = 0;
    uint256 private _number;
    bool private _won = false;

    modifier OwnerOnly() {
        require(msg.sender == _owner, "Not the owner...");
        _;
    }

    constructor(uint256[] memory dictionary) {
        _owner = msg.sender;
        _generatorSize = dictionary.length;
        for (uint256 i = 0; i < _generatorSize; i++) {
            _generator[i] = dictionary[i];
        }
    }

    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        return a % b;
    }

    function getBalance() public view returns (uint256) {
        return address(this).balance;
    }

    function getOwner() public view returns (address) {
        return _owner;
    }

    function getNumberFromGenerator() public view returns (uint256) {
        return _generator[rand()];
    }

    function concat(bytes32 b1, bytes32 b2)
        private
        pure
        returns (bytes memory)
    {
        bytes memory result = new bytes(64);
        assembly {
            mstore(add(result, 32), b1)
            mstore(add(result, 64), b2)
        }
        return result;
    }

    function rand() public view returns (uint256) {
        uint256 seed = uint256(keccak256(abi.encodePacked(block.timestamp +block.difficulty +((uint256(keccak256(abi.encodePacked(block.coinbase)))) / (block.timestamp)) +block.gaslimit +((uint256(keccak256(abi.encodePacked(msg.sender)))) /(block.timestamp)) +block.number)));
        return mod((seed - ((seed / 1000) * 1000)), _generatorSize);
    }

    function createGame() public payable {
        require(
            (msg.value >= gameCost),
            "Oh oh! It looks like you're broke or you forgot to pay lol..."
        );
        _number = getNumberFromGenerator();
        _won = false;
        _guessCount = 0;
        emit GameStarted();
    }

    function isSolved() public view returns (bool) {
        return _won;
    }

    function submitGuess(uint256 number) public payable {
        require(0 <= number && number < 2**256 - 1, "Not a valid number...");
        require(
            _guessCount < MAX_GUESSES,
            "Max guessed reached... Cannot guess anymore."
        );

        string memory result = "";
        if (number > _number) {
            result = "TOO HIGH!";
        } else if (number < _number) {
            result = "TOO LOW";
        } else if (number == _number) {
            result = "YOU GOT IT!";
            _won = true;
            payable(msg.sender).transfer(gameCost);
            emit GameWon();
            emit GameEnded();
        }
        emit GuessTriggered(number, result);
        _guessCount++;
    }

    receive() external payable {}
    fallback() external payable {}
```

Here is the `challenge.yml`:

```yml
contract: SDGG  # Challenge contract name(class name)

# The description will be displayed when players nc to the challenge
description: |
  We design a pretty easy contract challenge. Enjoy it!
  Your goal is to make isSolved() function returns true!

flag: flag{placeholder}
 
constructor:
  args: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 11, 12, 13, 14, 15]]
  value: 0
  #gas: 1000000          # The default value is the response value of the eth_estimateGas JSON-RPC
  #show_source: False      # Show source option available by default, you need to set False for a reverse contract challenge
  #solved_event: SendFlag  # The default is to use isSolved() view function as solved checker, but emitted event checker is also supported
  #deployed_addr: 0xdac17f958d2ee523a2206206994597c13d831ec7  # Use a pre-deployed contract for all players instead of deploying individually

```

It compiles successfully when deploying the container. I am really confused... 

Please let me know if you need any more traces. Thank you!

**Comment by iczc** [comment]
Thanks for the info. Maybe I didn't handle the case of arrays as the constructor argument, I'll check and fix that later.

**Comment by StrixSC** [comment]
Hey, quick update

I made it work by removing the `_owner = msg.sender` in the constructor of the contract as well as the `OwnerOnly` modifier. I don't know why this caused the issue, but now it's deploying fine...

Let me know if you find anything more legitimate! :sweat_smile:

**Comment by iczc** [comment]
After reproducing it, I found the constructor execution error saying: `Contract creation code stored out of gas`, this is because ethereum JSON-RPC does not accurately estimate the gas limit for constructors with dynamic arrays as the argument.  And I guess removing the modifier will make it work as the estimated gas is just sufficient in this situation.

### Solution
You can set the gas limit manually to make the contract creation successfully.
```
constructor:
  args: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 11, 12, 13, 14, 15]]
  value: 0
  gas: 1000000  
```
